Liker/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('LikerApp.urls',namespace= 'LikerApp')),
    path('',include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

LikerApp/urls.py
from django.urls import path
from . import views

app_name='LikerApp'

urlpatterns=[
    path('',views.loginUser,name='loginUser'),
    path('signup/',views.register,name='signup'),
    path('login/', views.loginUser, name='loginUser'),
    path('profile/<str:pk>',views.profilePage,name="profile"),
    path('private_Post/<str:pk>/',views.personalPost,name='private_Post'),
    path('post/',views.publicPost,name='public_post'),
    path('createPost/<str:pk>/',views.createPost,name='create_post'),
    path('like/',views.like_post,name='like_post'),
    path('logout/',views.logoutUser,name='logout_user'),
    path('createComment/<str:pk>',views.comment_post,name='createComment'),
    path('displayComment/<str:pk>',views.display_comments,name='displayComment'),
    path('profile_pic/',views.customerSettings,name='settings'),
    path('specificPost/<str:pk>/',views.specificPost, name="specificPost"),
    path('delete/<str:pk>/',views.delete,name='delete'),
    path('changeUsername/',views.changeUsername,name="changeUsername"),
    path('settings/',views.settingsPage),
    path('searchPage/',views.searchPost,name='searchPost')
    ]

Liker/LikerApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)
    add_time=models.DateTimeField(auto_now_add=True,null=True)
    profile_pic=models.ImageField(null=True,blank=True,upload_to='static/images',default='cave.jpg')
    
    def __str__(self):
        return str(self.user)

def create_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)
        
post_save.connect(create_profile,sender=User)

def update_profile(sender,instance,created,**kwargs):
    if created == False:
        instance.profile.save()
post_save.connect(update_profile,sender=User)


class Post(models.Model):
    profile=models.ForeignKey(Profile,on_delete=models.SET_NULL,null=True,related_name='profile')
    title=models.CharField(max_length=200,null=True)
    content=models.TextField(max_length=1500,null=True)
    liked=models.ManyToManyField(User,default=None, blank=True, related_name='liked')
    
    def __str__(self):
        return str(self.title)
    
    @property
    def num_likes(self):
        return self.liked.all().count()
    
  
class Like(models.Model):
    LIKE_CHOICES = (
        ('Like','Like'),
        ('Unlike','Unlike')
    )
    user=models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    post=models.ForeignKey(Post,on_delete=models.SET_NULL, null=True)
    value = models.CharField(choices=LIKE_CHOICES, default=True, max_length=10)
    
    def __str__(self):
        return str(self.post)

class Comment(models.Model):
    Profile=models.ForeignKey(Profile,on_delete=models.CASCADE,null=True)
    post=models.ForeignKey(Post,on_delete=models.SET_NULL,null=True)
    content=models.TextField( null=True )

LikerApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)
    add_time=models.DateTimeField(auto_now_add=True,null=True)
    profile_pic=models.ImageField(null=True,blank=True,upload_to='static/images',default='profile_picture.jpg')
    def __str__(self):
        return str(self.user)

def create_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)
        
post_save.connect(create_profile,sender=User)

def update_profile(sender,instance,created,**kwargs):
    if created == False:
        instance.profile.save()
post_save.connect(update_profile,sender=User)


class Post(models.Model):
    profile=models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,related_name='profile')
    title=models.CharField(max_length=200,null=True)
    content=models.TextField(max_length=1500,null=True)
    liked=models.ManyToManyField(User,default=None, blank=True, related_name='liked')
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    
    def __str__(self):
        return str(self.title)
    
    @property
    def num_likes(self):
        return self.liked.all().count()
    
  
class Like(models.Model):
    LIKE_CHOICES = (
        ('Like','Like'),
        ('Unlike','Unlike')
    )
    user=models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    post=models.ForeignKey(Post,on_delete=models.SET_NULL, null=True)
    value = models.CharField(choices=LIKE_CHOICES, default=True, max_length=10)
    
    def __str__(self):
        return str(self.post)

class Comment(models.Model):
    Profile=models.ForeignKey(Profile,on_delete=models.CASCADE,null=True)
    post=models.ForeignKey(Post,on_delete=models.SET_NULL,null=True)
    content=models.TextField( null=True )

LikerApp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import *
from django import forms

class CreationUserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']

class CreatePost(ModelForm):
    class Meta:
        model=Post
        fields='__all__'
        exclude=['likes']

class CreateComment(ModelForm):
    class Meta:
        model=Comment
        fields="__all__"
        exclude=['user']



class SettingsForm(ModelForm):
    class Meta:
        model=Profile
        fields=['profile_pic']
        exclude=['user']

class UsernameForm(UserCreationForm):
    class Meta:
        model=User
        fields=["username"]
        

LikerApp/views.py
from django.http import HttpResponseRedirect,Http404
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from .forms import *
from django.contrib import messages
from .models import *
from .decorators import *
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.db.models import Q 
#from .filters import SearchFilter

# Create your views here.
@unauthenticated_user
def register(request):
    createUser=CreationUserForm()
    if request.method == 'POST':
        createUser=CreationUserForm(request.POST)
        if createUser.is_valid():
            createUser.save()
    context={
        'createUser':createUser
    }
    return render(request,'pages/registerPage.html',context)

@unauthenticated_user
def loginUser(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('LikerApp:public_post')
        else:
            messages.info(request,'username or password is incorrect ')
    return render(request,'pages/login.html')

def logoutUser(request):
    logout(request)
    return redirect('LikerApp:loginUser')

@login_required(login_url='/login')
def publicPost(request):
    posts=Post.objects.all().order_by('-created_at')
    profile= Profile.objects.all()
    #searchFilter = SearchFilter( request.GET, queryset=posts)
    #posts=searchFilter.qs
    user= request.user
    context={
        'posts':posts,
        'user':user,
        'profile':profile,
        #'searchFilter':searchFilter
    }
    return render(request,'pages/publicPost.html/',context)
@login_required(login_url='/login')
def searchPost(request):
    query=request.GET.get("search")
    if query:
        result=Post.objects.filter( Q(title__icontains=query)| Q(content__icontains=query) | Q(profile__user__username__icontains=query))
    else:
        result=""
    context={
        'result':result
    }
    return render(request,'pages/postSearch.html',context)
@login_required(login_url='/login')
def specificPost(request,pk):
    post=Post.objects.get(id=pk)
    context={
        "post":post
    }
    return render(request,'pages/specificPost.html/',context)

@login_required(login_url='/login')
def personalPost(request,pk):
    personalPosts=Post.objects.filter(profile=Profile.objects.get(id=pk))
    context={
        "personalPosts":personalPosts
    }
    return render(request,"pages/personalPost.html",context)

@login_required(login_url='/login')
def profilePage(request,pk):
    profile=Profile.objects.get(id=pk)
    post=profile.post_set.all()
    context={
        'profiles':profile,
        'posts':post
    }
    return render(request,'pages/profilePage.html',context)

@login_required(login_url='/login')
def createPost(request,pk):
    profile=Profile.objects.get(id=pk)
    user= get_object_or_404(User,id=pk)
    if request.user != user:
        raise Http404("You are not authorized to view this page.")
    orderFormSet=inlineformset_factory(Profile,Post, fields=('title','content'),extra=1)
    formset=orderFormSet(queryset=Post.objects.none(),instance=profile)
    if request.method == 'POST':
        formset=orderFormSet(request.POST,instance=profile)
        if formset.is_valid():
            formset.save()
            return redirect('/post')
    context={
        'formset':formset,
    }
    return render(request,'pages/createPost.html',context)

@login_required(login_url='/login')
def delete(request,pk):
    post=Post.objects.get(id=pk)
    if request.method == "POST":
        post.delete()
        return redirect("/post")
    context={"item":post}
    return render (request,'pages/delete.html',context)

@login_required(login_url='/login')
def like_post(request):
    user=request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        
        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)
            
        like, created = Like.objects.get_or_create(user=user, post_id=post_id)
        
        if not created:
            if like.value == 'Like':
                like.value = ' Unlike'
            else:
                like.value = 'Like'
            
            like.save()
        context={
            'post':post_obj
        }
    return redirect( reverse('LikerApp:specificPost',args=[post_obj.id]) )
@login_required(login_url='/login')
def comment_post(request,pk):
    #users=request.user
    posts=Post.objects.get(id=pk)
    commentFormSet=inlineformset_factory(Post,Comment,fields=('content',),extra=1)
    formset=commentFormSet(queryset=Comment.objects.none(),instance=posts)
    if request.method == 'POST':
        formset=commentFormSet(request.POST,instance=posts)
        if formset.is_valid():
            formset.save()
            return redirect("/post")
    context={
        "formset":formset,
    }
    return render(request,'pages/createComment.html',context)

@login_required(login_url='/login')
def display_comments(request,pk):
    posts=Post.objects.get(id=pk)
    pcomment=Comment.objects.filter(post=posts)
    context={
        'pcomment':pcomment
    }
    return render(request,'pages/displayComment.html',context)

#Change profile picture
@login_required(login_url='/login')
def customerSettings(request):
    customerForm= SettingsForm(instance=request.user.profile)
    if request.method == "POST":
        customerForm=SettingsForm(request.POST,request.FILES, instance=request.user.profile)
        if customerForm.is_valid():
            customerForm.save()
            #return redirect('/post')
        else:
            return redirect('/')
    context={
        'form':customerForm
    }
    return render(request,'pages/customer_settings.html',context)

@login_required(login_url='/login')
def changeUsername(request):
    uForm=UsernameForm(instance = request.user)
    if request.method == "POST":
        uForm = UsernameForm(request.POST, instance= request.user)
        uForm.save()
    context={
        'uForm':uForm
    }
    return render(request,'pages/changeUsername.html',context)

@login_required(login_url='/login')
def settingsPage(request):
    return render(request,'pages/settings.html/')

LikerApp/templates/pages/changeUsername.html
{% load static %}
<!DOCTYPE html>
<html>    
    <head>
        <title> Change Username and Password</title>
        <link rel="stylesheet" href={% static '/css/main.css'%}>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body class="changeUsernameBody">
        <div><a href="/post/"><span class="logo">  Thoughts & Scribbles   </span></a></div>
        <form class="changeUsernameForm" method="POST">
            {% csrf_token %}
            {% for field in uForm%}
                <div class='usernameLabel'>{{field.label}}</div>
                <div class='usernameField'>{{field}}</div>
            {% endfor %}
            <input type="submit" value="Change">
        </form>
    </body>
</html>

LikerApp/templates/pages/createComment.html
{% load static %}
<html>
    <head>
        <title> Add Comment </title>
        <link rel="stylesheet" href={% static '/css/main.css'%}>
    </head>
    <body class="createCommentBody">
        <form class="createCommentForm" method="POST">
        {% csrf_token %}
        <div class="AddCommentDiv">
        {{formset}}
        </div>
        <input class="submitComment" type="submit" value="post">
        </form>
    </body>
</html>

LikerApp/templates/pages/createPost.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href={% static '/css/main.css'%}>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <nav>
            <a href="/post/"><span class="logo">  Thoughts & Scribbles   </span></a>        </nav>
            <form method="POST" action="" class="createPost">
            {% csrf_token %}
            <div class="form">
            <div class="formset">
                {{formset}} 
                <input type="submit" value="Publish">
            </div>

            </div>

        </form>
    </body>
</html>

LikerApp/templates/pages/customer_settings.html
{% load static %}
<html>
    <head>
        <title> Profile Image </title>
        <link rel="stylesheet" href={% static '/css/main.css'%}>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    
    <body class="pic_settingBody">
        <div><a href="/post/"><span class="logo">  Thoughts & Scribbles   </span></a></div>
        <div class="setting_img_div">
            <img class="setting_img" width="100px" src="{{request.user.profile.profile_pic.url}}">
        </div>
        <form class='settings_form' enctype="multipart/form-data" method="POST" >
            <p><b>Warning:</b> Do not check the check box, if you do your account will probably be lost.</p>
            {% csrf_token %}
            {% for field in form%}
                {{field}}
            {% endfor %}
            <input class="settings_button" type='submit' value="Change">
        </form> 
    </body>
</html>

LikerApp/templates/pages/delete.html
<form method="POST" action="">
    {% csrf_token %}
    Are you sure you want to delete {{item}}
    <a href="/post/"> <button> Cancel </button> </a>
    <a href ="/post/"> <input type="submit" name="Accept"></a>
</form>

LikerApp/templates/pages/displayComment.html
{% load static %}
<html>
    <head>
        <title>Post</title>
        <link rel="stylesheet" href={% static '/css/main.css'%}>
    </head>
    <body class="displayCommentBody">
        {% for obj in pcomment %}
        <div class="displayComments">
        {{ obj.content }} 
        {{ obj.Profile.user}}
        </div>
    {% endfor %}
    </body>
</html>

LikerApp/templates/pages/login.html
{% load static %}
<html>
    <head>
        <title>Login</title>
        <link rel="stylesheet" href={% static '/css/main.css'%}>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body class="loginBody">
        <form method="POST" class="loginForm">
        {% csrf_token %} 
            <input class="username" type="text" name="username" placeholder="Username">
            <input class="password" type="password" name="password" placeholder='Password'>
            <input class="submit" type="submit" value="Log in">
            <p class="DHA"> Don't Have an account yet <a class="signUpHl" href="/signup"> Sign Up</a> </p>
        </form>
    </body>
</html>

LikerApp/templates/pages/personalPost.html
{% extends 'pages/publicPost.html'%}
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href={% static '/css/main.css'%}>
    </head>
<body>
{% block content %}
<div>
    <img width="100px" src="{{ request.user.profile.profile_pic.url}}">
</div>
<main class='main'>
{% for personalPost in personalPosts%}
<a href="/specificPost/{{ personalPost.id }}">  

    <div class="post">
        <div class='title'> {{personalPost.title}} </div>
        <div class = 'content'> {{personalPost.content}} </div>
    </div>
</a>
<div> <a href="/delete/{{personalPost.id}}"> Delete Post </a></div>
{% endfor %}
</main>
{% endblock %}
</body>
</html>

LikerApp/templates/pages/postSearch.html
{% extends 'pages/publicPost.html'%}
{% load static %}
<html>
    <head>
        <title>Search</title>
        <link rel='stylesheet' href={% static '/css/main.css'%}>
    </head>
    <body>
        {% block content %}

        <main class="main">
            {% for post in result%}
            <!-- For individual posts -->
            <a href="/specificPost/{{ post.id }}">   
                <div class="post">
                    <div class="author"> {{post.profile}}</div>
                    <div class="title">  {{post.title }} </div>
                    <div class="content">  {{post.content }} </div>
                <br>
                </div>
            </a>
            {% endfor %}
           
        </main>

        {% endblock %}
    </body>
</html>

LikerApp/templates/pages/profilePage.html
{{request.user}}
<a href={% url 'create_post' profiles.id %}> <input type="submit" value="Create Blog " > </a>

LikerApp/templates/pages/publicPost.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Public Post</title>
    <link rel="stylesheet" href={% static '/css/main.css'%}>
</head>
    <body>
        {% block content %}

        {% endblock %}
        
        <nav class="navbar">
            <span class="nav_section1">   
                <div class="profile_img">
                    <img class="img" src="{{ request.user.profile.profile_pic.url}}">
                </div>
                <span class="username">{{request.user}}</span>
            </span>
            <a href="/post/"><span class="logo">  Thoughts & Scribbles   </span></a>
            <span class="nav_section2">
                <span class="nav1"> <a href="/private_Post/{{request.user.id}}/" > personal posts</a></span>
                <span class="nav1"> <a href="/createPost/{{request.user.id}}/" > Create Post</a></span>
                <span class="nav1"> <a href="/settings">Settings</a></span>
                <span class="nav1"> <a href="/logout/">  Logout  </a> </span>
            </span>
        </nav>
        <div class='searchDiv'>
            <form class="searchForm" method='GET' action='/searchPage'>
                <input type='text' class='textInput' name='search' placeholder='Welcome to Thoughts and Scribbles'>
                <button type='submit' class='submitInput'> <img src="{% static 'images/search.png' %}"> </button>
            </form>
        </div>

      <!--  <div class='searchDiv'> 
                <form method="get" class="searchForm">
                    <span class="searchTitle">{{searchFilter.form}}</span>
                    <input value="search" type="submit">
                </form>
            </div>
        -->

        <main class="main">
            {% for post in posts %}
            <!-- For individual posts -->
            <a href="/specificPost/{{ post.id }}">   
                <div class="post">
                    <div class="author"> {{post.profile}}</div>
                    <div class="title">  {{post.title }} </div>
                    <div class="content">  {{post.content }} </div>
                <br>
                </div>
            </a>
            {% endfor %}
           
        </main>
        
    </body>
</html>

LikerApp/templates/pages/registerPage.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body class="registerBody">
    <form method="POST" class="registerForm" >
      <p class="AHA" > Already have an account? <a class="loginLink" href="/login">Sign in</a> </p>

      {% csrf_token %}
      {% for form in createUser %}
        <div class="label">{{ form.label }}</div>
        <div class="registerForm">{{ form }}</div>
        <div class="registerErrors">{{ form.errors }}</div>
        <br>
      {% endfor %}
      <input class="registerSubmit"type="submit" value="Sign Up">
    </form>
  </body>
</html>

LikerApp/templates/pages/settings.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>My Page</title>
    <link rel="stylesheet" href={% static '/css/main.css'%}>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body class="settingsBody">
    <a href="/profile_pic/">
      <div class="pro_Pic">Change Profile Picture</div>
    </a>
    <a href="/changeUsername">
      <div class="useName">Change Username and Password</div>
    </a>
  </body>
</html>

LikerApp/templates/pages/specificPost.html
{% load static %}
<html>
    <head>
        <title>Post</title>
        <link rel="stylesheet" href={% static '/css/main.css'%}>
    </head>
    <body class="specificPostBody">
        <div class="specificPostAurthor"> author {{post.profile}}</div>
        <div class="specificPostTitle">  {{ post.title }}  </div>
        <div class="specificPostContent"> {{ post.content }} </div>

        <form class="specificPostForm" action="{% url 'LikerApp:like_post' %}" method='POST' class="ui form">
            {% csrf_token %}
            <input type='hidden' name='post_id' value="{{ post.id}}">
            {% if user not in post.liked.all %}
                <button class="LikeButton" type='submit'> Like </button>
            {% else %}
                <button class="UnLikeButton" type='submit'> Unlike</button>
            {% endif %}
        </form>

        <strong> {{ post.liked.all.count }} likes </strong>
        <div class="AddComment"> <a href="/createComment/{{post.id}}"> <button> Add Comment </button> </a> </div>
        <div class="DisplayComment"> <a href="/displayComment/{{post.id}}"> <button> Display Comment </button> </a> </div>
    </body>
</html>